# Generated by Django 3.0.1 on 2020-08-12 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
                ('time_period', models.CharField(choices=[('O', 'OLD TESTAMENT'), ('N', 'NEW TESTAMENT'), ('*', 'N/A')], default='X', max_length=10)),
                ('answer_type', models.CharField(choices=[('N', 'NAME'), ('P', 'PLACE'), ('AC', 'ACTION'), ('R', 'REASON'), ('I', 'ITEM'), ('AN', 'ANIMAL')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[(1, 'EASY'), (2, 'MEDIUM'), (3, 'HARD')], default=1, max_length=10)),
                ('answer_type', models.CharField(choices=[('N', 'NAME'), ('P', 'PLACE'), ('AC', 'ACTION'), ('R', 'REASON'), ('I', 'ITEM'), ('AN', 'ANIMAL')], max_length=10)),
                ('time_period', models.BooleanField(default=False)),
                ('jesus', models.BooleanField(default=False)),
                ('doctrine', models.BooleanField(default=False)),
                ('prophecy', models.BooleanField(default=False)),
                ('geneology', models.BooleanField(default=False)),
                ('gospel', models.BooleanField(default=False)),
                ('miracle', models.BooleanField(default=False)),
                ('history', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('categories', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.QuestionCategory')),
                ('choices', models.ManyToManyField(max_length=200, to='trivia_game.Choice')),
            ],
        ),
    ]
