# Generated by Django 3.0.1 on 2020-08-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='time_period',
            field=models.CharField(choices=[('O', 'OLD TESTAMENT'), ('N', 'NEW TESTAMENT'), ('*', 'N/A')], default='X', max_length=1),
        ),
    ]
