# Generated by Django 3.0.1 on 2020-08-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0002_auto_20200812_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
    ]
