# Generated by Django 3.0.1 on 2020-08-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0003_auto_20200815_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'ordering': ['question']},
        ),
    ]
