# Generated by Django 3.0.1 on 2020-09-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0004_auto_20200815_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accurate_question', to='trivia_game.Choice'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='difficulty',
            field=models.CharField(choices=[('1', 'EASY'), ('2', 'MEDIUM'), ('3', 'HARD')], default=1, max_length=10),
        ),
    ]
