# Generated by Django 3.0.1 on 2020-09-07 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0005_auto_20200906_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accurate_questions', to='trivia_game.Choice'),
        ),
    ]
