# Generated by Django 3.0.11 on 2021-08-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0007_auto_20200906_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer_type',
            field=models.CharField(choices=[('N', 'NAME'), ('PL', 'PLACE'), ('AC', 'ACTION'), ('R', 'REASON'), ('I', 'ITEM'), ('AN', 'ANIMAL'), ('PE', 'PERSON')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='answer_type',
            field=models.CharField(choices=[('N', 'NAME'), ('PL', 'PLACE'), ('AC', 'ACTION'), ('R', 'REASON'), ('I', 'ITEM'), ('AN', 'ANIMAL'), ('PE', 'PERSON')], max_length=10),
        ),
    ]
